extends: relaxed

rules:
  line-length:
    max: 200
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: false
  comments:
    min-spaces-from-content: 1
  document-start:
    present: false
