services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC #Change to your timezone
    volumes:
      - ${PWD}/fresh-rss:/config
    ports:
      - 127.0.0.1:88:80 #Localhost only with reverse-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - your-network # Change Value
networks:
    your-network: # Change Value
      external: true
